# Generated by Django 4.1.1 on 2023-06-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='impotant',
            new_name='important',
        ),
    ]
